name: Github-actions-example.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v2
    - uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: lts/*
    - run:
        npm i
        cd frontend
        node -v
        npm i
        #npm build
        #npm run test
        #npm run e2e

