name: Github-actions-example.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted


    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run:
        npm i
        cd frontend
        npm i
        npm build
        npm run test
        npm run e2e

